// Core node modules
import fs from 'node:fs';
import path from 'node:path';
import * as url from 'node:url';

// Installed modules
import nunjucks from 'nunjucks';

// Voyzu framework
import framework from 'voyzu-framework-01';

/**
 * Route entry point.
 * @param {object} httpRequest An object conforming to the http-request model.
 * @param {object} context The context passed by vserver or vmock.
 * @param {object} pathParams An object with all path parameters passed to this route.
 * @returns {object} An object conforming to the http-response model.
 */
export async function fulfill(httpRequest, context, pathParams) {

  const pkg = framework.cache.get ('pkg');
  const webDir = framework.cache.get ('webDir');
  const buildNumber = framework.cache.get ('buildNumber');
  const thisDirName = url.fileURLToPath(new URL('.', import.meta.url));

  const headerTemplatePath = path.join(webDir,'templates', 'header.html');
  let headerHtml = fs.readFileSync(headerTemplatePath).toString();
  headerHtml = nunjucks.renderString(headerHtml, {});

  const navTemplatePath = path.join(webDir, 'templates', 'nav.html');
  let navHtml = fs.readFileSync(navTemplatePath).toString();
  navHtml = nunjucks.renderString(navHtml, {});

  const footerTemplatePath = path.join(webDir,'templates', 'footer.html');
  let footerHtml = fs.readFileSync(footerTemplatePath).toString();
  footerHtml = nunjucks.renderString(footerHtml, {});

  let html = fs.readFileSync(path.join(thisDirName, 'index.html')).toString();
  html = nunjucks.renderString(html, {
    footerHtml,
    headerHtml,
    navHtml,
    pageDescription: `page generated by voyzu framework component ${pkg.name} ${pkg.version} build ${buildNumber}`
  });

  const httpResponseBase = {
    http_code: 200,
    response_data: html,
    response_type: framework.enums.HTTP_RESPONSE_TYPE.HTML
  };

  return framework.model.generateModel(httpResponseBase, framework.models.httpResponse);
}