// Core node modules
import fs from 'node:fs';
import path from 'node:path';

// Installed modules
import nunjucks from 'nunjucks';

// Voyzu framework
import framework from 'voyzu-framework-01';

/**
 * Route entry point.
 * @param {object} httpRequest An object conforming to the http-request model.
 * @param {object} context The context passed by vserver or vmock.
 * @param {object} pathParams An object with all path parameters passed to this route.
 * @returns {object} An object conforming to the http-response model.
 */
export async function fulfill(httpRequest, context, pathParams) {

  const pkg = framework.cache.get('pkg');
  const webDir = framework.cache.get('webDir');
  const buildNumber = framework.cache.get('buildNumber');

  const headerTemplatePath = path.join(webDir, 'templates', 'header.html');
  let headerHtml = fs.readFileSync(headerTemplatePath).toString();
  headerHtml = nunjucks.renderString(headerHtml, {});

  const navTemplatePath = path.join(webDir, 'templates', 'nav.html');
  let navHtml = fs.readFileSync(navTemplatePath).toString();
  navHtml = nunjucks.renderString(navHtml, {});

  const footerTemplatePath = path.join(webDir, 'templates', 'footer.html');
  let footerHtml = fs.readFileSync(footerTemplatePath).toString();
  footerHtml = nunjucks.renderString(footerHtml, {});

  const templatePath = path.join(webDir, 'templates');

  let jsCode = '\n\n<script>';
  jsCode += framework.web.ui.alert.getCode();
  jsCode += `\n\n${framework.web.ui.binding.getCode()}\n\n`;
  jsCode += `\n\n${framework.web.ui.validation.getCode()}\n\n`;
  jsCode += '\n\n</script>\n\n';

  const flights = framework.cache.get('flights');
  const airlines = [...new Set(flights.map(flight => flight.airline))];

  const airlinesForSelect = [];
  for (const airline of airlines) {
    airlinesForSelect.push({
      text: airline,
      value: airline.replaceAll(' ', '_')
    });
  }

  let html = fs.readFileSync(path.join(templatePath, 'flight.html')).toString();
  html = nunjucks.renderString(html, {
    airlines: airlinesForSelect,
    flight: JSON.stringify({}),
    footerHtml,
    headerHtml,
    jsCode,
    navHtml,
    pageDescription: `page generated by voyzu framework component ${pkg.name} ${pkg.version} build ${buildNumber}`,
    pageHeading: 'Add new flight',
    saveMethod: 'POST',
    saveUrl: '/api/flights',
  });

  const httpResponseBase = {
    http_code: 200,
    response_data: html,
    response_type: framework.enums.HTTP_RESPONSE_TYPE.HTML
  };

  return framework.model.generateModel(httpResponseBase, framework.models.httpResponse);
}